#!/bin/bash
#
# Copyright Institut für Telematik, Universität zu Lübeck, 2011
#
# Author: Sönke Nommensen
#
# Server-side Git post receive script to deploy new files to the
# locally installed Apache and restart NodeJS server.
#

server_location="/var/www/parking/nodejs"
lib_location="/var/www/parking/nodejs/lib"
git_location="/var/www/parking"

server_script="server"

lib_scripts="scraper
history
geo"

# Server stop
forever stop ${server_location}/${server_script}.js

# Remove old JS files
if [ -a ${server_location}/${server_script}.js ]
then
    rm ${server_location}/${server_script}.js
fi

for script in ${lib_scripts}
do
    if [ -a ${lib_location}/${script}.js ]
    then
        rm ${lib_location}/${script}.js
    fi
done

# Pull changes from master
cd ${git_location}
env -i git pull origin master

# Compile new coffee scripts
coffee --compile ${server_location}/${server_script}.coffee

for script in ${lib_scripts}
do
    coffee --compile ${lib_location}/${script}.coffee
done

# Server start
forever start --append -o ${server_location}/out.log -e ${server_location}/err.log ${server_location}/${server_script}.js
