#!/bin/bash
#
# Copyright Institut für Telematik, Universität zu Lübeck, 2011
#
# Author: Sönke Nommensen
#
# Server-side Git post receive script to deploy new files to the
# locally installed Apache and restart NodeJS server.
#

script_location="/var/www/parking/nodejs"
git_location="/var/www/parking"

server_script="server"

additional_scripts="scraper
geo"

# Server stop
forever stop ${script_location}/${server_script}.js

# Remove old JS files
if [ -a ${script_location}/${server_script}.js ]
then
    rm ${script_location}/${server_script}.js
fi

for script in ${additional_scripts}
do
    if [ -a ${script_location}/${script}.js ]
    then
        rm ${script_location}/${script}.js
    fi
done

# Pull changes from master
cd ${git_location}
env -i git pull origin master

# Compile new coffee scripts
coffee --compile ${script_location}/${server_script}.coffee

for script in ${additional_scripts}
do
    coffee --compile ${script_location}/${script}.coffee
done

# Server start
forever start --append -o ${script_location}/out.log -e ${script_location}/err.log ${script_location}/${server_script}.js
