#!/bin/bash

input="geo
scraper
server"

compile() {
    for script in ${input}
    do
        if [ -a ${script}.js ] 
        then    
            rm ${script}.js
        fi    
        echo "Compiling ${script}.coffee => ${script}.js"
        coffee --compile ${script}.coffee
    done
}

cleanup() {
    for script in ${input}
    do
        if [ -a ${script}.js ] 
        then          
            rm ${script}.js
            echo Deleted ${script}.coffee            
        fi    
    done
}

# See how we were called
case "$1" in
compile)
      compile
      ;;
cleanup)
      cleanup
      ;;
*)
      echo "Usage: $0 {compile|cleanup}"
esac
