#!/bin/bash

server="server"

lib="lib/geo
lib/history
lib/scraper"

compile() {
    if [ -a ${server}.js ]
    then
        rm ${server}.js
    fi
    echo "Compiling ${server}.coffee => ${server}.js"
    coffee --compile ${server}.coffee

    for script in ${lib}
    do
        if [ -a ${script}.js ] 
        then    
            rm ${script}.js
        fi    
        echo "Compiling ${script}.coffee => ${script}.js"
        coffee --compile ${script}.coffee
    done
}

cleanup() {
    if [ -a ${server}.js ]
    then
        rm ${server}.js
        echo Deleted ${server}.js
    fi

    for script in ${lib}
    do
        if [ -a ${script}.js ] 
        then          
            rm ${script}.js
            echo Deleted ${script}.js            
        fi    
    done
}

# See how we were called
case "$1" in
compile)
      compile
      ;;
cleanup)
      cleanup
      ;;
*)
      echo "Usage: $0 {compile|cleanup}"
esac
